// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShedBuilder.Api.Data;

#nullable disable

namespace ShedBuilder.Api.Data.Migrations
{
    [DbContext(typeof(ShedDbContext))]
    partial class ShedDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShedBuilder.Api.Models.Design", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DepthFeet")
                        .HasColumnType("integer")
                        .HasColumnName("depth_feet");

                    b.Property<int>("DepthInches")
                        .HasColumnType("integer")
                        .HasColumnName("depth_inches");

                    b.Property<int>("HeightFeet")
                        .HasColumnType("integer")
                        .HasColumnName("height_feet");

                    b.Property<int>("HeightInches")
                        .HasColumnType("integer")
                        .HasColumnName("height_inches");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("RoofPitch")
                        .HasColumnType("numeric")
                        .HasColumnName("roof_pitch");

                    b.Property<string>("RoofType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("roof_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("WidthFeet")
                        .HasColumnType("integer")
                        .HasColumnName("width_feet");

                    b.Property<int>("WidthInches")
                        .HasColumnType("integer")
                        .HasColumnName("width_inches");

                    b.HasKey("Id");

                    b.ToTable("designs");
                });

            modelBuilder.Entity("ShedBuilder.Api.Models.DesignVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DepthFeet")
                        .HasColumnType("integer")
                        .HasColumnName("depth_feet");

                    b.Property<int>("DepthInches")
                        .HasColumnType("integer")
                        .HasColumnName("depth_inches");

                    b.Property<Guid>("DesignId")
                        .HasColumnType("uuid")
                        .HasColumnName("design_id");

                    b.Property<int>("HeightFeet")
                        .HasColumnType("integer")
                        .HasColumnName("height_feet");

                    b.Property<int>("HeightInches")
                        .HasColumnType("integer")
                        .HasColumnName("height_inches");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<decimal>("RoofPitch")
                        .HasColumnType("numeric")
                        .HasColumnName("roof_pitch");

                    b.Property<string>("RoofType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("roof_type");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.Property<int>("WidthFeet")
                        .HasColumnType("integer")
                        .HasColumnName("width_feet");

                    b.Property<int>("WidthInches")
                        .HasColumnType("integer")
                        .HasColumnName("width_inches");

                    b.HasKey("Id");

                    b.HasIndex("DesignId");

                    b.ToTable("design_versions");
                });

            modelBuilder.Entity("ShedBuilder.Api.Models.DesignVersion", b =>
                {
                    b.HasOne("ShedBuilder.Api.Models.Design", "Design")
                        .WithMany("Versions")
                        .HasForeignKey("DesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Design");
                });

            modelBuilder.Entity("ShedBuilder.Api.Models.Design", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
