{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "shed-builder.fullname" . }}-ingress
  labels:
    {{- include "shed-builder.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.apiHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "shed-builder.fullname" . }}
                port:
                  number: {{ .Values.api.port }}
    {{- if .Values.ui.enabled }}
    - host: {{ .Values.ingress.uiHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "shed-builder.fullname" . }}-ui
                port:
                  number: {{ .Values.ui.port }}
    {{- end }}
{{- end }}
