apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shed-builder.fullname" . }}-db
  labels:
    {{- include "shed-builder.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
  jwt-secret-key: {{ .Values.api.jwtSecretKey | b64enc | quote }}
