apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shed-builder.fullname" . }}-ui
  labels:
    {{- include "shed-builder.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: ui
    spec:
      containers:
        - name: ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ui.port }}
          env:
            - name: API_HOST
              value: {{ include "shed-builder.fullname" . }}-api
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
