{{- if .Values.ui.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shed-builder.fullname" . }}-nginx
  labels:
    {{- include "shed-builder.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location /api/ {
            proxy_pass http://{{ include "shed-builder.fullname" . }}:{{ .Values.api.port }}/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
{{- end }}
