ui:
  enabled: false

api:
  corsAllowedOrigins: "https://shed-builder.dev.heathrobotics.io"

ingress:
  enabled: true
  apiHost: shed-builder-api.dev.heathrobotics.io
  uiHost: shed-builder.dev.heathrobotics.io
